.PHONY: all clean act friends miiverse ssl

all: act friends miiverse ssl

act:
	@make -C act

friends:
	@make -C friends
	
miiverse:
	@make -C miiverse
	
ssl:
	@make -C ssl

clean:
	@make -C act clean
	@make -C friends clean
	@make -C miiverse clean
	@make -C ssl clean
