.PHONY: all clean act friends http miiverse ssl socket

all: act friends http miiverse ssl socket

act:
	@make -C act

friends:
	@make -C friends

http:
	@make -C http

miiverse:
	@make -C miiverse

ssl:
	@make -C ssl

socket:
	@make -C socket

clean:
	@make -C act clean
	@make -C friends clean
	@make -C http clean
	@make -C miiverse clean
	@make -C ssl clean
	@make -C socket clean
