.PHONY: all clean act friends juxt ssl

all: act friends juxt ssl

act:
	@make -C act

friends:
	@make -C friends
	
juxt:
	@make -C juxt
	
ssl:
	@make -C ssl

clean:
	@make -C act clean
	@make -C friends clean
	@make -C juxt clean
	@make -C ssl clean
